### ISSUE TITLE
Wolfram Alpha Support

### ISSUE THREAD

**Issue by hugohabicht01** [AdriBloober/DiscordSearchBot#27]
Add support for Wolfram Alpha either with just sending a link to the answer of a question or embed, depending on the lenght of the answer

**Comment by AdriBloober** [comment]
Toll, noch mehr für meine TODO.

Wolltest du nicht eigentlich die ddg Intigration machen mhhh

**Comment by AdriBloober** [comment]
Der MathBot besitzt bereits das Feature
