### ISSUE TITLE
Allow to use more than one word on lmgtfy

### ISSUE THREAD

**Issue by luwol03** [AdriBloober/DiscordSearchBot#56]
![Screenshot_2020-05-07-23-52-21](https://user-images.githubusercontent.com/60048565/81348147-da113180-90bd-11ea-80ca-9c7bb31697c3.png)

**Comment by AdriBloober** [comment]
Duplicate of https://github.com/AdriBloober/DiscordSearchBot/issues/55

**Comment by luwol03** [comment]
Da war ich wohl zu langsam!
