### ISSUE TITLE
delete function for ?lmgtfy

### ISSUE THREAD

**Issue by luwol03** [AdriBloober/DiscordSearchBot#60]
add a deletebutton with the :wastebasket: icon also to the ```?lmgtfy <query>``` command.
[Link zu #botcommands auf dem morpheus discord server](https://discordapp.com/channels/326817317075943424/331088117480030208/715860391514865706)

**Comment by AdriBloober** [comment]
Ok:

I would implement the lmgtfy as ctx type, so we have all features from normal ctx types like google or StackOverflow.
